ACTIVE_LEARNING:
  desired_acc: 0.042
  lambda: 5.
  n_samples: 5
  initial_valid_ratio: 0.2
  valid_ratio: 3
  converge_initial: False
  scheduler_initial: True
  max_initial_epochs: 200
  max_epochs_worker: 20
  max_final_epochs: 200
  intermediate_epochs: 10
  patience: 20
  max_MD_steps: 10000
  max_set_size: 300
  valid_skip: 5
  sanity_skip: 10
  ensemble_size: 5
  c_x: -0.1
  dataset_dir: "./data"
  skip_step: 5 # step to skip in sampling MLFF MD
  threshold: 0.15 # uncertainty threshold for AL; temporary
  num_trajectories: 3 # number of trajectories to from sample in parallel
  species_dir: "/project/home/p200243/tcp_software/aims_240507_library/FHIaims/species_defaults/defaults_2020/light"
  aims_lib_path: "/project/home/p200243/tcp_software/aims_240507_library/libaims.240627.scalapack.mpi.so"

MD:
  stat_ensemble: NVT
  thermostat: Langevin
  temperature: 200
  timestep: 0.5
  friction: 0.001
  seed: 42
  
