ACTIVE_LEARNING:
  desired_acc: 0.042
  lambda: 5.
  n_samples: 10
  initial_valid_ratio: 0.2
  valid_ratio: 3
  converge_initial: True
  scheduler_initial: True
  max_initial_epochs: 400
  max_epochs_worker: 10
  max_final_epochs: 400
  intermediate_epochs: 5
  patience: 20
  max_MD_steps: 10
  max_set_size: 5
  valid_skip: 1
  sanity_skip: 5
  ensemble_size: 2
  c_x: -0.1
  dataset_dir: "./data"
  skip_step: 1 # step to skip in sampling MLFF MD
  threshold: 0.15 # uncertainty threshold for AL; temporary
  num_trajectories: 4 # number of trajectories to from sample in parallel

  # only for simulation of procedure
  #path_to_trajectories: /home/tobias/Uni/Promotion/Research/aims_MLFF/data/naphtalene/nve_80K_extxyz/trajectories_for_sampling
  path_to_trajectories: /home/thenkes/Documents/Uni/Promotion/Research/aims_MLFF/data/naphtalene/nve_80K_extxyz/trajectories_for_sampling

MD:
  stat_ensemble: NVT
  thermostat: Langevin
  temperature: 300
  timestep: 1
  friction: 0.02
  seed: 42
  
