[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aims_PAX"
version = "0.1"
description = "Active learning for FHI-aims"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "Placeholder" }
authors = [
    { name = "Tobias Henkes", email = "tobias.henkes@uni.lu" }
]
keywords = []
classifiers = [
    "Programming Language :: Python :: 3"
]
dependencies = [
    "ase",
    "numpy",
    "mace-torch",
    "asi4py",
    "torch",
    "pyyaml",
]

[project.optional-dependencies]
parsl = ["parsl"]

[project.urls]
homepage = "https://github.com/tohenkes/aims_PAX"

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
aims_PAX = "aims_PAX.cli.__main__:main"
aims_PAX-initial-ds = "aims_PAX.cli.create_initial_ds:main"
aims_PAX-al = "aims_PAX.cli.al_procedure_only:main"
aims_PAX-scratch = "aims_PAX.cli.scratch_train:main"
aims_PAX-atomic-energies = "aims_PAX.cli.get_atomic_energies:main"
aims_PAX-test-ensemble = "aims_PAX.cli.test_ensemble:main"
aims_PAX-recalculate = "aims_PAX.cli.recalculate_data:main"