ACTIVE_LEARNING:
  desired_acc: 0
  valid_ratio: 0.3 # e.g. 0.3 means 30% of the data is used for validation
  converge_al: True
  converge_best: False
  max_epochs_worker: 10
  max_convergence_epochs: 50
  intermediate_epochs_al: 5
  convergence_patience: 50
  max_MD_steps: 100000
  max_set_size: 11
  valid_skip: 5
  analysis_skip: 50
  ensemble_size: 4
  c_x: -0.5
  skip_step_mlff: 25 # step to skip in sampling MLFF MD
  num_trajectories: 4 # number of trajectories to from sample in parallel
  species_dir: "/mnt/irisgpfs/projects/tcp/FHIaims-221103/species_defaults/defaults_2020/light"
  aims_lib_path: "/mnt/irisgpfs/projects/tcp/thenkes/FHIaims/FHIaims/build_lib/libaims.250711.scalapack.mpi.so"
  parallel: True
  #freeze_threshold_dataset: 11

INITIAL_DATASET_GENERATION:
  valid_ratio: 0.3 # e.g. 0.3 means 30% of the data is used for validation
  n_samples: 4
  converge_initial: False
  scheduler_initial: True
  valid_skip: 5
  max_initial_epochs: 10
  ensemble_size: 4
  skip_step_initial: 25 # step to skip in sampling initial MD
  initial_sampling: mace-mp0
  initial_foundational_size: "small"
  convergence_patience: 50
  desired_acc: 0
  lambda: 20.
  max_initial_set_size: 11
  species_dir: "/mnt/irisgpfs/projects/tcp/FHIaims-221103/species_defaults/defaults_2020/light"
  aims_lib_path: "/mnt/irisgpfs/projects/tcp/thenkes/FHIaims/FHIaims/build_lib/libaims.250711.scalapack.mpi.so"



MD:
  stat_ensemble: NVT
  thermostat: Langevin
  temperature: 500
  timestep: 1.
  friction: 0.001

MISC:
  create_restart: True
  analysis: False
  dataset_dir: "./data"
  #path_to_geometry: "/home/users/thenkes/phd/aimsMLFF/test_install/aims-PAX/examples/multi_system/geometries_small"
  
