CLUSTER:
  type: slurm
  project_name: 'EXAMPLE'
  parsl_options:
    nodes_per_block: 1
    init_blocks: 1
    min_blocks: 1
    max_blocks: 8
    label: 'EXAMPLE'

  slurm_str: |
    #!/bin/bash -l
    #SBATCH --time=01:30:00
    #SBATCH -N 1
    #SBATCH --ntasks-per-node=12
    #SBATCH -p batch
    #SBATCH -J parsl_test
  worker_str: |
    source /home/users/thenkes/miniconda3/bin/activate aimspax
    module load toolchain/intel
    ulimit -s unlimited

  launch_str: srun /mnt/irisgpfs/projects/tcp/emoerman/software/FHI-aims/FHIaims/build/aims.250507.scalapack.mpi.x >> aims.out
  clean_dirs: True
  calc_dir: "/home/users/thenkes/phd/aimsMLFF/test_install/aims-PAX/examples/multi_system/calc"

ACTIVE_LEARNING:
  desired_acc: 0
  lambda: 20.
  n_samples: 4
  valid_ratio: 0.3 # e.g. 0.3 means 30% of the data is used for validation
  converge_initial: False
  converge_al: True
  converge_best: False
  scheduler_initial: True
  max_initial_epochs: 20
  max_epochs_worker: 10
  max_final_epochs: 50
  intermediate_epochs: 5
  patience: 50
  max_MD_steps: 5000
  max_set_size: 30
  valid_skip: 5
  analysis_skip: 50
  ensemble_size: 4
  c_x: -0.1
  dataset_dir: "./data"
  skip_step_initial: 25 # step to skip in sampling initial MD
  skip_step_mlff: 25 # step to skip in sampling MLFF MD
  num_trajectories: 2 # number of trajectories to from sample in parallel
  species_dir: "/mnt/irisgpfs/projects/tcp/FHIaims-221103/species_defaults/defaults_2020/light"
  aims_lib_path: "/mnt/irisgpfs/projects/tcp/thenkes/FHIaims/FHIaims/build_lib/libaims.250711.scalapack.mpi.so"
  analysis: True
  initial_sampling: mace-mp0
  initial_foundational_size: "small"
  parallel: False
  #freeze_threshold_dataset: 11

MD:
  stat_ensemble: NVT
  thermostat: Langevin
  temperature: 500
  timestep: 1.
  friction: 0.001
  seed: 42

MISC:
  create_restart: True
  path_to_geometry: "/home/users/thenkes/phd/aimsMLFF/test_install/aims-PAX/examples/multi_system/geometries" 
