ACTIVE_LEARNING:
  desired_acc: 0
  lambda: 20.
  n_samples: 4
  valid_ratio: 0.3 # e.g. 0.3 means 30% of the data is used for validation
  converge_initial: False
  converge_al: True
  converge_best: False
  scheduler_initial: True
  max_initial_epochs: 10
  max_epochs_worker: 10
  max_final_epochs: 50
  intermediate_epochs: 5
  patience: 50
  max_MD_steps: 100000
  max_set_size: 11
  valid_skip: 5
  analysis_skip: 50
  ensemble_size: 4
  c_x: -0.5
  dataset_dir: "./data"
  skip_step_initial: 25 # step to skip in sampling initial MD
  skip_step_mlff: 25 # step to skip in sampling MLFF MD
  num_trajectories: 4 # number of trajectories to from sample in parallel
  species_dir: "/mnt/tier2/project/p200243/tcp_software/FHIaims_master_branch/FHIaims/species_defaults/defaults_2020/light"
  aims_lib_path: "/mnt/tier2/project/p200243/tcp_software/FHIaims_master_branch/FHIaims/build_lib/libaims.250507.scalapack.mpi.so"
  analysis: True
  initial_sampling: mace-mp0
  initial_foundational_size: "small"
  parallel: False
  #freeze_threshold_dataset: 11

MD:
  stat_ensemble: NVT
  thermostat: Langevin
  temperature: 500
  timestep: 1.
  friction: 0.001
  seed: 42

MISC:
  create_restart: True
  
