ACTIVE_LEARNING:
  desired_acc: 0.000042
  lambda: 15.
  n_samples: 4
  valid_ratio: 0.3 # e.g. 0.3 means 30% of the data is used for validation
  converge_initial: False
  converge_al: True
  converge_best: True
  scheduler_initial: True
  max_initial_epochs: 30
  max_epochs_worker: 10
  max_final_epochs: 200
  intermediate_epochs: 10
  patience: 20
  max_MD_steps: 100
  max_set_size: 15
  valid_skip: 5
  sanity_skip: 10
  ensemble_size: 2
  c_x: -0.1
  dataset_dir: "./data"
  skip_step_initial: 10 # step to skip in sampling initial MD
  skip_step_mlff: 5 # step to skip in sampling MLFF MD
  num_trajectories: 3 # number of trajectories to from sample in parallel
  species_dir: "/project/home/p200243/tcp_software/aims_master_090824/FHIaims/species_defaults/defaults_2020/light"
  aims_lib_path: "/project/home/p200243/tcp_software/aims_master_090824/libaims.241114.scalapack.mpi.so"
  analysis: True
  initial_sampling: mace-mp0
  initial_foundational_size: "small"
  parallel: False

MD:
  stat_ensemble: NPT
  barostat: NPT
  temperature: 300
  timestep: 0.5
  externalstress: 1
  ttime: 25
  pfactor: 75

MISC:
  create_restart: True
  
